### ISSUE TITLE
Could not find a package configuration file provided by "pybind11"

### ISSUE THREAD

**Issue by genkv** [real-stanford/flingbot#4]
Hello,

I followed the instructions exactly in README. 

Entered the docker environment using this command:

```
sudo docker exec -t -i 0e912bc162b8 /bin/bash
```

When I tried to compile the .so inside the docker, I got the following error:

```
CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/workspace/flingbot/PyFlex/bindings/build/CMakeFiles/CMakeOutput.log".
See also "/workspace/flingbot/PyFlex/bindings/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
```

Interestingly, I was able to compile successfully outside of docker (in the conda environment). But when I run the sample command, I got the following error:

```
raceback (most recent call last):
  File "run_sim.py", line 1, in <module>
    from utils import (
  File "/home/workspace/flingbot/utils.py", line 2, in <module>
    from environment import SimEnv, TaskLoader
  File "/home/workspace/flingbot/environment/__init__.py", line 1, in <module>
    from .simEnv import SimEnv
  File "/home/workspace/flingbot/environment/simEnv.py", line 3, in <module>
    from .utils import (
  File "/home/workspace/flingbot/environment/utils.py", line 7, in <module>
    import pyflex
ImportError: /home/workspace/flingbot/PyFlex/bindings/build/pyflex.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument
```

**Comment by canhe173** [comment]
> Hello,
> 
> I followed the instructions exactly in README.
> 
> Entered the docker environment using this command:
> 
> ```
> sudo docker exec -t -i 0e912bc162b8 /bin/bash
> ```
> 
> When I tried to compile the .so inside the docker, I got the following error:
> 
> ```
> CMake Error at CMakeLists.txt:5 (find_package):
>   By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "pybind11",
>   but CMake did not find one.
> 
>   Could not find a package configuration file provided by "pybind11" with any
>   of the following names:
> 
>     pybind11Config.cmake
>     pybind11-config.cmake
> 
>   Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
>   "pybind11_DIR" to a directory containing one of the above files.  If
>   "pybind11" provides a separate development package or SDK, be sure it has
>   been installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/workspace/flingbot/PyFlex/bindings/build/CMakeFiles/CMakeOutput.log".
> See also "/workspace/flingbot/PyFlex/bindings/build/CMakeFiles/CMakeError.log".
> make: *** No targets specified and no makefile found.  Stop.
> ```
> 
> Interestingly, I was able to compile successfully outside of docker (in the conda environment). But when I run the sample command, I got the following error:
> 
> ```
> raceback (most recent call last):
>   File "run_sim.py", line 1, in <module>
>     from utils import (
>   File "/home/workspace/flingbot/utils.py", line 2, in <module>
>     from environment import SimEnv, TaskLoader
>   File "/home/workspace/flingbot/environment/__init__.py", line 1, in <module>
>     from .simEnv import SimEnv
>   File "/home/workspace/flingbot/environment/simEnv.py", line 3, in <module>
>     from .utils import (
>   File "/home/workspace/flingbot/environment/utils.py", line 7, in <module>
>     import pyflex
> ImportError: /home/workspace/flingbot/PyFlex/bindings/build/pyflex.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument
> ```

Hi, I'm having the same problem, did you solve the problem?

**Comment by zcswdt** [comment]
> Hello,
> 
> I followed the instructions exactly in README.
> 
> Entered the docker environment using this command:
> 
> ```
> sudo docker exec -t -i 0e912bc162b8 /bin/bash
> ```
> 
> When I tried to compile the .so inside the docker, I got the following error:
> 
> ```
> CMake Error at CMakeLists.txt:5 (find_package):
>   By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "pybind11",
>   but CMake did not find one.
> 
>   Could not find a package configuration file provided by "pybind11" with any
>   of the following names:
> 
>     pybind11Config.cmake
>     pybind11-config.cmake
> 
>   Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
>   "pybind11_DIR" to a directory containing one of the above files.  If
>   "pybind11" provides a separate development package or SDK, be sure it has
>   been installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/workspace/flingbot/PyFlex/bindings/build/CMakeFiles/CMakeOutput.log".
> See also "/workspace/flingbot/PyFlex/bindings/build/CMakeFiles/CMakeError.log".
> make: *** No targets specified and no makefile found.  Stop.
> ```
> 
> Interestingly, I was able to compile successfully outside of docker (in the conda environment). But when I run the sample command, I got the following error:
> 
> ```
> raceback (most recent call last):
>   File "run_sim.py", line 1, in <module>
>     from utils import (
>   File "/home/workspace/flingbot/utils.py", line 2, in <module>
>     from environment import SimEnv, TaskLoader
>   File "/home/workspace/flingbot/environment/__init__.py", line 1, in <module>
>     from .simEnv import SimEnv
>   File "/home/workspace/flingbot/environment/simEnv.py", line 3, in <module>
>     from .utils import (
>   File "/home/workspace/flingbot/environment/utils.py", line 7, in <module>
>     import pyflex
> ImportError: /home/workspace/flingbot/PyFlex/bindings/build/pyflex.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument
> ```

Hello, have you successfully trained?

**Comment by zcswdt** [comment]
> > Hello,
> > I followed the instructions exactly in README.
> > Entered the docker environment using this command:
> > ```
> > sudo docker exec -t -i 0e912bc162b8 /bin/bash
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I tried to compile the .so inside the docker, I got the following error:
> > ```
> > CMake Error at CMakeLists.txt:5 (find_package):
> >   By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
> >   asked CMake to find a package configuration file provided by "pybind11",
> >   but CMake did not find one.
> > 
> >   Could not find a package configuration file provided by "pybind11" with any
> >   of the following names:
> > 
> >     pybind11Config.cmake
> >     pybind11-config.cmake
> > 
> >   Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
> >   "pybind11_DIR" to a directory containing one of the above files.  If
> >   "pybind11" provides a separate development package or SDK, be sure it has
> >   been installed.
> > 
> > 
> > -- Configuring incomplete, errors occurred!
> > See also "/workspace/flingbot/PyFlex/bindings/build/CMakeFiles/CMakeOutput.log".
> > See also "/workspace/flingbot/PyFlex/bindings/build/CMakeFiles/CMakeError.log".
> > make: *** No targets specified and no makefile found.  Stop.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Interestingly, I was able to compile successfully outside of docker (in the conda environment). But when I run the sample command, I got the following error:
> > ```
> > raceback (most recent call last):
> >   File "run_sim.py", line 1, in <module>
> >     from utils import (
> >   File "/home/workspace/flingbot/utils.py", line 2, in <module>
> >     from environment import SimEnv, TaskLoader
> >   File "/home/workspace/flingbot/environment/__init__.py", line 1, in <module>
> >     from .simEnv import SimEnv
> >   File "/home/workspace/flingbot/environment/simEnv.py", line 3, in <module>
> >     from .utils import (
> >   File "/home/workspace/flingbot/environment/utils.py", line 7, in <module>
> >     import pyflex
> > ImportError: /home/workspace/flingbot/PyFlex/bindings/build/pyflex.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument
> > ```
> 
> Hi, I'm having the same problem, did you solve the problem?

Hello, have you successfully trained?
